### ISSUE TITLE
Eth0 interface is not working

### ISSUE THREAD

**Issue by rkamudhan** [hustcat/sriov-cni#1]
I am getting the following error when running SRIOV plugin with i40e SRIOV enabled NIC(X710) in the centOS 7 (Linux 3.10.0-327.28.3.el7.x86_64) env. 

Error in the ipam.ConfigureIface(args.IfName, result) as follows - `{\n    \"code\": 100,\n    \"msg\": \"failed to set \\\"eth0\\\" UP: device or resource busy\"\n}"`

Couldn't bring up the moved VF interface inside the container, the container creation is failing.

**Comment by hustcat** [comment]
@rkamudhan You can configure VF manually, to check if it can be successful:

```
#!/bin/bash

vf=2
ns=ns2
nic=$(ls "/sys/class/net/eth1/device/virtfn$vf/net/")
echo "VF:$nic"

ip netns add $ns
ip link set $nic netns $ns
ip netns exec $ns ip link set $nic up
ip netns del $ns
```

**Comment by rkamudhan** [comment]
Related to the kernel, so closing this issue..
