### ISSUE TITLE
Where is  the ip  from ?

### ISSUE THREAD

**Issue by louyunli** [hustcat/sriov-cni#12]
I found the  fixipam only to  check whether the request ip  is in the subnet be configured.
However ,who give the   request IP?    pass it by  the  env virable  CNI_ARGS ?

**Comment by hustcat** [comment]
Yeah, pass `IP` with CNI_ARGS. Of course, you can use other IPAM plugin.

**Comment by hustcat** [comment]
@louyunli Can we close this?
