### ISSUE TITLE
assign pf to one container

### ISSUE THREAD

**Issue by lubinsz** [hustcat/sriov-cni#14]
Hi,
Sometimes, there are many ethernet card in one PC and we need to assign PF to one container.
So can I deliver the patch for this case?
The logic code can be this:
if args.VF > 0 , assign vf directly
if args.VF = 0, alloc a free VF
if args.VF < 0, assign PF.

**Comment by rkamudhan** [comment]
@lubinsz Can you explain the use case of this? I am interest in understanding the use case.

**Comment by lubinsz** [comment]
@rkamudhan We have many ethernet cards in one PC. We want to select one card, and use IPAM+DHCP as load-balance or firewall for data-plane. In fact, I have enabled the code for PF, and also enabled dpdk patch for this project. Test job was also finished for K8S. If allowed, I will deliver the patch for PF & DPDK. In fact, if we use DPDK to accelerate it, we don't need vf any more. DPDK with PF has the best performance.

**Comment by rkamudhan** [comment]
@lubinsz we are working on the forked verion of SRIOV CNI, which support DPDK on the SRIOV VF https://github.com/Intel-Corp/sriov-cni. I am working in upstream those code into SRIOV-CNI. I think SRIOV VF use case is equally important Cloud segment, SRIOV VF allow Network SLAs, If we use PF, we can't do the bandwidth allocation and orchestrate it through the OCE. Please let me know your thoughts on it.

**Comment by ghost** [comment]
@rkamudhan I see. You have finished the job of DPDK.  But could I deliver the code for PF use case? For firewall pods, we only need PF, don't need to care about the bandwidth allocation and orchestrate. 
Because we have more than 4 ethernet cards in one node. For other k8s pods, we use VF, but for pods with firewall/load-balancer, we only use PF.

**Comment by rkamudhan** [comment]
@lubinsz, Got your point :) , Is that your use case is sort of multi network or different network within the cluster depending on the pods application ?  @hustcat Is that your view is also the same on this use case ?

**Comment by ghost** [comment]
@rkamudhan In a typical 5G base station, there are several ethernet cards in one board in fact. For the pre-application of K8S pods, we only need enable PF for it.

**Comment by ghost** [comment]
@rkamudhan Yes. We should use multi network. Some pods need it. Genie-cni we used. But for the pre-application of K8S pods, 1 cni is good.  --- 1 type

**Comment by rkamudhan** [comment]
DPDK doesn't use the IPAM information at all, I am confused with it usage now

**Comment by lubinsz** [comment]
@rkamudhan if we use DPDK+pf, we can add the management cni or not, like flannel or calico.
If we only use PF, we only need 1 cni. In fact, when we use DPDK+PF, we don't need l3 any more. We only deploy mini ip-stack which get from 6WIND on this pods. Or we can deploy mtcp in it. The pods with DPDK+PF is unique, we deploy it as the Daemonset. This pre-application pods will check the packets, and divide the flow to other pods, like l2 or callp pods. For L2 and CALLP pods, they have the multiple cni.

**Comment by lubinsz** [comment]
@rkamudhan  if we use the feature of l2fwd, for example, maybe we should forward the packets into another node, we should enable 2 sriov-cni at least.

**Comment by lubinsz** [comment]
@rkamudhan 
for this case, I will only enable PF, not touch the code of DPDK. Also I have improved other codes, such as: don't rename the vf as dev*, just use the old card name. 
PS: latency is very important for 5G/firewall/load-balancer, so other features related to latency maybe we should add.

**Comment by lubinsz** [comment]
Previously, we use share memory & hardware fast-path between L1 & L2. And now we use PCIE & software fast-path(ODP or DPDK). For L2 & upper layer, maybe we will use some freescale or Marvell boards. Such as  Marvell MacchiatoBIN, the card between L1 &L2 without SRIOV, so we only enabled PF mode for SRIOV-CNI, and deploy the whole solution with multiple cni by using K8S. For other modules, we still use VF mode with SRIOV-CNI.

**Comment by hustcat** [comment]
@lubinsz  Sorry about the delay replay.  Do you mean add  PF without  SRIOV to one container ? I think it's reasonable when have multiple ethernet cards. 

Moreover , I think we can discussion the DPDK in another issue. WDYT? @lubinsz @rkamudhan

**Comment by lubinsz** [comment]
@hustcat 
Yes. Assign the specific card into the container by checking the value of args.VF.

sample logic code is like this:
in setupVF()
        if args.VF > 0 {
                vfIdx = int(args.VF)
                vfDevName, err = getVFDeviceName(masterName, vfIdx)
                if err != nil {
                        return err
                }
        } else if args.VF == 0 {
                // alloc a free virtual function
                if vfIdx, vfDevName, err = allocFreeVF(masterName); err != nil {
                        return err
                }
        } else if args.VF < 0 {
                // alloc PF
                vfDevName = masterName
        }

**Comment by hustcat** [comment]
Yeah, I think it's reasonable. WDYT? @rkamudhan

**Comment by rkamudhan** [comment]
@hustcat

**Comment by hustcat** [comment]
Close for #19
