### ISSUE TITLE
don't return error in cmdDel

### ISSUE THREAD

**Issue by SchoIsles** [hustcat/sriov-cni#18]
sometimes, container exits unexpectly, or removed by other way.
kubernetes evictSandboxes method try to clean all unavailable sandboxes of the pod, but encountered an error at del cni network. report error logs like this
```
Sep 28 13:58:16 hostname kubelet[2081]: W0928 13:58:16.324567    2081 cni.go:258] CNI failed to retrieve network namespace path: Error: No such container: 463c9db192540a2d697772a72db4853c92ff73a1fa85b56b7b1a145ae8505118    
Sep 28 13:58:16 hostname kubelet[2081]: E0928 13:58:16.328854    2081 cni.go:312] Error deleting network: failed to open netns %!!(MISSING)q(<nil>): failed to Statfs "": no such file or directory    
Sep 28 13:58:16 hostname kubelet[2081]: E0928 13:58:16.329353    2081 docker_sandbox.go:239] Failed to stop sandbox "463c9db192540a2d697772a72db4853c92ff73a1fa85b56b7b1a145ae8505118": Error response from daemon: {"message":"No such container: 463c9db192540a2d697772a72db4853c92ff73a1fa85b56b7b1a145ae8505118"}    
Sep 28 13:58:16 hostname kubelet[2081]: E0928 13:58:16.329555    2081 remote_runtime.go:114] StopPodSandbox "463c9db192540a2d697772a72db4853c92ff73a1fa85b56b7b1a145ae8505118" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "tengine-3391168842-1cbzd_debug" network: failed to open netns %!!(MISSING)q(<nil>): failed to Statfs "": no such file or directory
Sep 28 13:58:16 hostname kubelet[2081]: E0928 13:58:16.329583    2081 kuberuntime_gc.go:154] Failed to stop sandbox "463c9db192540a2d697772a72db4853c92ff73a1fa85b56b7b1a145ae8505118" before removing: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "tengine-3391168842-1cbzd_debug" network: failed to open netns %!!(MISSING)q(<nil>): failed to Statfs "": no such file or directory
```

cmdDel try to GetNS but failed, so kubelet continue retry at next loop.

if try to open a container's netns failed, releaseVF is not needed.
I made a test, start container and mv vf device into it's net ns, and then killed the container, device return into the vf's net directory and can be reused.

so, we can ignore error if GetNS failed, and continue try ipam delete, and ignore errors too.
at the same time, I think there need a log handler write errors into file

**Comment by hustcat** [comment]
K8s will still call CNI/DEL command even if container exits unexpectly ?

**Comment by SchoIsles** [comment]
@hustcat yes, the author suggestd below
https://github.com/kubernetes/kubernetes/issues/43014#issuecomment-287164444
and some cni plugins did this already

**Comment by jellonek** [comment]
I've approach the same issue.
Even if there is no netns (e.x. after node reboot) the plugin should call IPAM to release address and fail only if IPAM returned an error. Also IPAM in this time should not return any error if the issue was not critical (but it's out of scope of this plugin).

**Comment by rkamudhan** [comment]
@jellonek @hustcat  I will fix this bug. Will create PR in couple of day.

**Comment by jellonek** [comment]
@rkamudhan just look on what i proposed for intel fork. I can simply prepare the same change there in a matter of minutes instead of couple of days (to be more precise, i'm doing that right now).

**Comment by jellonek** [comment]
As I said - done in #21.
