### ISSUE TITLE
Rebase instead of merge

### ISSUE THREAD

**Issue by ahalimx86** [hustcat/sriov-cni#23]
Hi,
The last commit 72acb4f has now 2 parents (491092c + 3b2571d ) because of merging the pull request "Fix lack of netns during network teardown" from #21  . This introduces some unnecessary complication on the git tree if we want to go back in history for some reason. Some git tools such a Gerrit setup doesn't allow any merge commit to be pushed. This can be avoided if we do ["Rebase and merge pull requests" ](https://github.com/blog/2243-rebase-and-merge-pull-requests) instead of merge. This can be fixed easily before more pull requests are merged into which can complicate things further.

**Comment by hustcat** [comment]
@ahalim-intel , I can remove the merge commit [72acb4f](https://github.com/hustcat/sriov-cni/commit/72acb4f349a827ebb4353dbe8839a6f6d89aa4e3) as follows:

```
# git checkout master
# git rebase -i 39b5648fa0edc87a145baee7ac837e20e6db7cdc
# git push -f origin master
```
Am I right?

**Comment by dmoneil2** [comment]
looks good dude
git rebase -i %sha before the branches diverged%

https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by ahalimx86** [comment]
@hustcat Yes, that should work. There is good article on interactive rebase: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history you might find usefull in addition to what @dmoneil2 mentioned above.

**Comment by hustcat** [comment]
Done!
