### ISSUE TITLE
anomalous system reboot

### ISSUE THREAD

**Issue by SchoIsles** [hustcat/sriov-cni#26]
Hi, dears
In my test enviroment, sometimes there encountered an anomalous system reboot while do deployment rolling update.

I'm sure added "intel_iommu=on iommu=pt" into kernel cmdline. BIOS configurtion enabled VT-d and SR-IOV enabled.  set sriov_numvfs to 63

I made a test

1. create a statefulset so pods can be create or delete one by one after the previous one success
2. increase replicas to 30
3. decrease replicas to 0

repeat step 2&3, after 5 cycles, at increase step , system reboot, reproduce fault.
no log leaves for troubleshoot

Does anyone encounter the same problem?

My env:
256G memory
82599 Intel® 10 Gigabit Ethernet
ubuntu 16.04 x86_64
kernel version 4.10.0-35
ixgbe version: 4.4.0-k
ixgbevf version: 3.2.2-k

**Comment by rkamudhan** [comment]
@okletswin, can you explain more the testing ?

**Comment by SchoIsles** [comment]
@rkamudhan I will try to make more detail
There has a simple statefulset named nginx, pod's image is nginx, nodeSelector is point to the single specified host who's cni plugin is use sriov.

write a script, make a loop to increase and decrease the replicas      

```bash
function getPodNum() {
    kubectl get statefulset nginx -n debug | grep nginx | awk '{print $3}'
}

function increase() {
    kubectl -n debug scale statefulset nginx --replicas $1
}

function decrease() {
    kubectl -n debug scale statefulset nginx --replicas 0
}

while true
do
    increase 30
    while true
    do
        currNum=`getPodNum`
        if [ "$currNum" == "30" ];then
            break 
        else
            sleep 1
        fi
    done
    
   decrease
    while true
    do
        currNum=`getPodNum`
        if [ "$currNum" == "0" ];then
            break
        else
            sleep 1
        fi
    done
done
```


then check the kubelet node's status if it is down

**Comment by SchoIsles** [comment]
@rkamudhan After change os from Ubuntu 16.04 to Centos 7.3, everything is OK.

**Comment by yuzhiquan** [comment]
we update lxbge also resolve this problem:
pci:`Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 `
lxbge version: `5.3.7`
kernel version: `4.4.138-1.el7.elrepo.x86_64`
linux release: `Release:	7.4.1708`
