### ISSUE TITLE
Introducing feature to  use all VFs in the master interface, instead of using only one VF...

### ISSUE THREAD

**Issue by rkamudhan** [hustcat/sriov-cni#6]
I am planning to upstream the code, with feature to check VFs in master interface, and use them instead of using one VF from the configuration file. @hustcat need your feedback

**Comment by hustcat** [comment]
It's great to add self-managed VFs in this plugin. However, I think we shoud reserve the way of  read VF from configuration file, this maybe flexible for user sometimes.

**Comment by rkamudhan** [comment]
yes, yes  I totally agree with you, if "VF" field is present, plugin will use it. If it is not present, then plugin goes to self-management mode.

**Comment by rkamudhan** [comment]
@hustcat  Please refer our new cni plugin *[Multus](https://github.com/Intel-Corp/multus-cni)*, I have used the [sriov-cni](https://github.com/Intel-Corp/sriov-cni) forked version of our implementation. I am planning to upstream each features of it.

**Comment by hustcat** [comment]
@rkamudhan I'v looked over Multus, it's a great job. However, I have some questions:
(1)There are some special reason for replace `Master` with `IF0` in [NetConf](https://github.com/Intel-Corp/sriov-cni/commit/a015f1a78c61925d24f1998e47f50a12fd15b9d1?diff=split#diff-8becae7a8222be03e1bcd86d9adaa117R24)?
(2)According to [CNI Spec](https://github.com/containernetworking/cni/blob/master/SPEC.md), we should use `args.IfName` as interface name in container, [IF0NAME](https://github.com/Intel-Corp/sriov-cni/commit/a015f1a78c61925d24f1998e47f50a12fd15b9d1?diff=split#diff-8becae7a8222be03e1bcd86d9adaa117R24) is not a good idea.
(3)I think we shoudn't delete `MAC` in `NetConf`, which make user can't set mac address for VF.
(4)At the same time, I think we shoud reserve the `VF` in `NetConf`, which let user have choice manage VF allocation themselves. Maybe we can change it from `int` to `string`, if value is empty, plugin can manage VF randomly.

**Comment by rkamudhan** [comment]
**(1)There are some special reason for replace Master with IF0 in NetConf?**
_No, it is just the naming convention, we can maintain the "master"_
**(2)According to CNI Spec, we should use args.IfName as interface name in container, IF0NAME is not a good idea.**
_Yes, you are right. By default Mutlus, will assign net0 or net1 to the minion plugins, in our case we using sriov as the minion plugins. We using flannel or calico as the master plugin, which assigned with the eth0 interface and their IP address and DNS is given back to the container. IF0NAME has been just an option in the sriov to give the interface name in the pods, if the option is omitted, then it works in the normal way._ 
**(3)I think we shoudn't delete MAC in NetConf, which make user can't set mac address for VF.**
_Yes, I will preserve it, and will change it accordingly_
**(4)At the same time, I think we shoud reserve the VF in NetConf, which let user have choice manage VF allocation themselves. Maybe we can change it from int to string, if value is empty, plugin can manage VF randomly.**
_Yes, my new commit, will have these features as you mentioned._

**Comment by hustcat** [comment]
@rkamudhan I add some changes for `Multus`'s config file:

```
{
    "name": "minion1-multus-demo-network",
    "type": "multus",
    "delegates": [
        {
            "type":"sriov",
            "netconf": {
                "type": "sriov",
                "master": "enp12s0f0",
                "mac": "aa:bb:cc:dd:ee:ff",
                "ipam": {
                        "type": "host-local",
                        "subnet": "10.56.217.0/24",
                        "rangeStart": "10.56.217.131",
                        "rangeEnd": "10.56.217.190",
                        "routes": [
                                { "dst": "0.0.0.0/0" }
                        ],
                        "gateway": "10.56.217.1"
                }
            },
            "ifname": "eth1"
        },
        {
            "type": "flannel",
            "masterplugin": true,
            "delegate": {
                        "isDefaultGateway": true
            }
        }
    ]
}
```
This structure let you don't need change CNI plugin's API which exist, such as sr-iov, macvlan, etc.
I think this maybe the right thing, WDYT?

**Comment by rkamudhan** [comment]
Ok now, I am getting your point, you basically don't want to mix up the multus network configuration to the current CNI plugins  ? Whether I am right on this ? I can change it, as you said. I will cross link this to issue in Multus. It is a good point

**Comment by hustcat** [comment]
Yeah, exactly, `Multus` should be independent with other CNI plugins.

**Comment by rkamudhan** [comment]
yes, I agree, I just need to change few line of code in Multus. Actually Multus is independent of the other CNI plugins, but I misplaced the Multus configuration inside the delegate netconf.

**Comment by hustcat** [comment]
Close #9
